<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MtAfkirDanDispenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mt_afkir_dan_dispen')->insert([
            [
                'nopol' => 'AD8033OG',
                'kapasitas' => 16,
                'kepemilikan' => 'PT. KARYO DIKROMO',
                'status' => 'All In Lokal',
                'tahun_pembuatan' => '2015-06-23',
                'merek' => 'HINO',
                'tmt_afkir' => '2025-06-23',
                'status_peremajaan' => 'DIREMAJAKAN',
                'operasi' => 'Tidak Aktif',
                'lama_afkir' => '9 Tahun 5 Bulan 2 Hari',
                'keterangan' => 'Proses di karoseri',
                'timeline_peremajaan' => 'Aug-26',
                'kelompok' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nopol' => 'AD8034OG',
                'kapasitas' => 16,
                'kepemilikan' => 'PT. KARYO DIKROMO',
                'status' => 'All In Lokal',
                'tahun_pembuatan' => '2015-06-23',
                'merek' => 'HINO',
                'tmt_afkir' => '2025-06-23',
                'status_peremajaan' => 'DIREMAJAKAN',
                'operasi' => 'Tidak Aktif',
                'lama_afkir' => '9 Tahun 5 Bulan 2 Hari',
                'keterangan' => 'Proses di karoseri',
                'timeline_peremajaan' => 'Aug-26',
                'kelompok' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nopol' => 'AG9707UW',
                'kapasitas' => 32,
                'kepemilikan' => 'PT. BINA SYAREKAH',
                'status' => 'All In Lokal',
                'tahun_pembuatan' => '2009-11-25',
                'merek' => 'HINO',
                'tmt_afkir' => '2024-11-25',
                'status_peremajaan' => 'DIREMAJAKAN',
                'operasi' => 'Tidak Aktif',
                'lama_afkir' => '15 Tahun 0 Bulan 0 Hari',
                'keterangan' => 'Menunggu balasan persetujuan kategori IV',
                'timeline_peremajaan' => '-',
                'kelompok' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nopol' => 'AD9728IG',
                'kapasitas' => 16,
                'kepemilikan' => 'PT. KARYO DIKROMO',
                'status' => 'All In Lokal',
                'tahun_pembuatan' => '2015-09-04',
                'merek' => 'HINO',
                'tmt_afkir' => '2025-09-04',
                'status_peremajaan' => 'DIREMAJAKAN',
                'operasi' => 'Tidak Aktif',
                'lama_afkir' => '9 Tahun 2 Bulan 21 Hari',
                'keterangan' => 'Proses di karoseri',
                'timeline_peremajaan' => 'Aug-26',
                'kelompok' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nopol' => 'L8334UH',
                'kapasitas' => 24,
                'kepemilikan' => 'PT. PUTRA WAHYU PERSADA',
                'status' => 'All In Lokal',
                'tahun_pembuatan' => '2015-12-30',
                'merek' => 'HINO',
                'tmt_afkir' => '2025-12-30',
                'status_peremajaan' => 'DIREMAJAKAN',
                'operasi' => 'Tidak Aktif',
                'lama_afkir' => '8 Tahun 10 Bulan 26 Hari',
                'keterangan' => 'Proses di karoseri',
                'timeline_peremajaan' => 'Aug-26',
                'kelompok' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nopol' => 'H8640OW',
                'kapasitas' => 32,
                'kepemilikan' => 'PT. SINAR',
                'status' => 'All In Lokal',
                'tahun_pembuatan' => '2010-10-26',
                'merek' => 'HINO',
                'tmt_afkir' => '2025-10-26',
                'status_peremajaan' => 'DIREMAJAKAN',
                'operasi' => 'Tidak Aktif',
                'lama_afkir' => '14 Tahun 0 Bulan 30 Hari',
                'keterangan' => 'Menunggu balasan persetujuan kategori IV',
                'timeline_peremajaan' => '-',
                'kelompok' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nopol' => 'AD8659EG',
                'kapasitas' => 32,
                'kepemilikan' => 'PT. KARYO DIKROMO',
                'status' => 'All In Lokal',
                'tahun_pembuatan' => '2010-11-22',
                'merek' => 'HINO',
                'tmt_afkir' => '2025-11-22',
                'status_peremajaan' => 'DIREMAJAKAN',
                'operasi' => 'Tidak Aktif',
                'lama_afkir' => '14 Tahun 0 Bulan 3 Hari',
                'keterangan' => 'Menunggu balasan persetujuan kategori IV',
                'timeline_peremajaan' => '-',
                'kelompok' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nopol' => 'AB8863EI',
                'kapasitas' => 32,
                'kepemilikan' => 'PT. WAHYU BARU SEJAHTERA',
                'status' => 'All In Lokal',
                'tahun_pembuatan' => '2010-11-11',
                'merek' => 'HINO',
                'tmt_afkir' => '2025-11-11',
                'status_peremajaan' => 'DIREMAJAKAN',
                'operasi' => 'Tidak Aktif',
                'lama_afkir' => '14 Tahun 0 Bulan 14 Hari',
                'keterangan' => 'Menunggu balasan persetujuan kategori IV',
                'timeline_peremajaan' => '-',
                'kelompok' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}